version: '3.8'
services:
  motioneye:
    container_name: motioneye
    image: ccrisan/motioneye:latest
    volumes:
      - ./etc:/etc/motioneye
      - ./var:/var/lib/motioneye
    ports:
      - "8765:8765"
    restart: unless-stopped
