services:
  mjpg-streamer:
    build: .
    ports:
      - "8080:8080"
    devices:
      - "/dev/video0:/dev/video0"
    environment:
      - RESOLUTION=${RESOLUTION}
      - FRAMERATE=${FRAMERATE}
    restart: unless-stopped
