version: '3.8'
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: America/Araguaina
      WEBPASSWORD: "admin"
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - "8053:53/tcp"
      - "8053:53/udp"
      - "8081:80"
    restart: unless-stopped
