version: '3.7'

services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: homeassistant
    volumes:
      - /mnt/data/homeassistant:/config
    environment:
      - TZ=America/Sao_Paulo
    restart: always
    network_mode: host
