version: '3.7'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - /mnt/data/mariadb:/var/lib/mysql
    restart: always
