version: '3.7'

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - "8096:8096"
    volumes:
      - /mnt/data/jellyfin:/config
      - /mnt/data/media:/media
    restart: always
