version: '3.7'

services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    ports:
      - "9091:9091"
      - "51413:51413"
    volumes:
      - /mnt/data/transmission:/config
      - /mnt/data/torrents:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TRANSMISSION_RPC_PASSWORD=secret
    restart: always
